### PR TITLE
sips formatcode and mimetypes

### PR DESCRIPTION
**Pull request by oliveregger**
this adds the format codes we would like to use for sIPS testing at the EU CAT 2024

### CODE REVIEW

**Comment by skbhaskarla** [comment]
@oliveregger @stl-steve-moore 
I have merged PR #600 into the develop branch file and updated some test metadata files. Since the updated codes seem to be used by XDS-I tests, I need you to verify the XDS-I metadata files are using the updated codes and not the old ones. 
https://github.com/usnistgov/iheos-toolkit2/compare/develop?expand=1

**Comment by oliveregger** [comment]
Thanks! Looks good to me.

I have question about https://github.com/usnistgov/iheos-toolkit2/compare/develop?expand=1#diff-24c2da058e90c6e405e592eb58579c034d9b7d92530fb8fd60aab02367dcd68b there (and in the following files)
changes from CT to urn:connectathon:bppc:foundational:policy and from Computed Tomography to Foundational Connectathon Read-Access Policy, does this make sense?

        <rim:Classification classificationScheme="urn:uuid:2c6b8cb7-8b2a-4051-b291-b1ae6a575ef4"
               classifiedObject="Document01" nodeRepresentation="CT"
               classifiedObject="Document01" nodeRepresentation="urn:connectathon:bppc:foundational:policy"
               objectType="urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:Classification"
               id="id_8">
            <rim:Slot name="codingScheme">
               <rim:ValueList>
                  <rim:Value>1.2.840.10008.2.6.1</rim:Value>
                  <rim:Value>1.3.6.1.4.1.21367.2017.3</rim:Value>
               </rim:ValueList>
            </rim:Slot>
            <rim:Name>
               <rim:LocalizedString value="Computed Tomography"/>
               <rim:LocalizedString value="Foundational Connectathon Read-Access Policy"/>
            </rim:Name>
         </rim:Classification>

I'm not an expert in XDS-I testing, but it will certainly come up, if there will be an issue changing the R-Codes to SNOMED CT, @stl-steve-moore do you know something about htis?

**Comment by skbhaskarla** [comment]
@oliveregger @stl-steve-moore 
Good catch! 
CT Code Coding scheme `1.2.840.10008.2.6.1` is not right in the metadata files, it should be `1.2.840.10008.2.16.4`. So when I ran the automatic tool, it detected an inconsistent value and simply replaced the code with something else. 
Can someone fix the metadata files? Thanks

**Comment by oliveregger** [comment]
i made PR for the develop branch

**Pull request merged**
